global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: kafka-adapter
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:8080' ]

  - job_name: pushgateway
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9091' ]

  - job_name: kafka
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9999' ]

  - job_name: node
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9100' ]


